// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPn0at22rFMntn0D0_CIgMZctoNrZ3sTI',
    appId: '1:340118541936:web:8c75177fba2b283c6fc6b5',
    messagingSenderId: '340118541936',
    projectId: 'service-app-1b286',
    authDomain: 'service-app-1b286.firebaseapp.com',
    storageBucket: 'service-app-1b286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGGxS7PbtGv8c39WxoAjR6EKiSEQ8yi4',
    appId: '1:340118541936:android:f04ed48d115d0c516fc6b5',
    messagingSenderId: '340118541936',
    projectId: 'service-app-1b286',
    storageBucket: 'service-app-1b286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc0h6JrvXVpSDultpnuEzIYaYgSyjU608',
    appId: '1:340118541936:ios:cb79a1e51628e0976fc6b5',
    messagingSenderId: '340118541936',
    projectId: 'service-app-1b286',
    storageBucket: 'service-app-1b286.appspot.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc0h6JrvXVpSDultpnuEzIYaYgSyjU608',
    appId: '1:340118541936:ios:b5ec669aedb81c606fc6b5',
    messagingSenderId: '340118541936',
    projectId: 'service-app-1b286',
    storageBucket: 'service-app-1b286.appspot.com',
    iosBundleId: 'com.example.serviceApp.RunnerTests',
  );
}
